In [1]:
import pandas as pd
import csv
import numpy as np
import matplotlib.pyplot as plt
import nltk
from nltk import word_tokenize

In [2]:
Sub_neighborhoods_df = pd.read_excel('Revised Sub-Neighborhoods.xlsx')
Sub_neighborhoods_df

,Census Tract#,Zipcode,Neighborhood,US Geonames Sub-neigborhood,Total Population,Black,Black Proportion,White,White Proportion,American Indian & Alaska Native,...,Male,Male Proportion,Female,Female Proportion,Lat,Long,Primary Sub-Neighborhood,Secondary Sub-Neighborhood,Teritriary Sub-Neighborhood(s),T-Stop/Commuter Rail
0,1.00,"02134, 02135",Brighton,NaN,5324,311,0.058415,3315,0.622652,0,...,2578,0.484222,2746,0.515778,42.361485,-71.138588,Lower Allston,Allston,Packard's Corner,Boston Landing
1,2.01,02135,Brighton,NaN,3991,237,0.059384,3164,0.792784,17,...,1800,0.451015,2191,0.548985,42.354066,-71.161168,Oak Square,Brighton,Hunnewell Hill,NaN
2,2.02,02135,Brighton,NaN,4272,263,0.061564,3031,0.709504,0,...,2175,0.509129,2097,0.490871,42.352605,-71.154344,Oak Square,Brighton,Allston,NaN
3,3.01,02135,Brighton,NaN,2946,216,0.073320,2203,0.747794,0,...,1650,0.560081,1296,0.439919,42.354144,-71.168827,Hunnwell Hill,Oak Square,NaN,NaN
4,3.02,02135,Brighton,NaN,3469,359,0.103488,2346,0.676276,25,...,1733,0.499568,1736,0.500432,42.347258,-71.167686,Brighton,St. Elizabeth's,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,9815.02,02151,East Boston,NaN,0,0,0.000000,0,0.000000,0,...,0,0.000000,0,0.000000,42.396367,-71.004379,Beachmont,Orient Heights,NaN,Beachmont
177,9816.00,02128,East Boston,NaN,0,0,0.000000,0,0.000000,0,...,0,0.000000,0,0.000000,42.388621,-70.993442,Orient Heights,Beachmont,NaN,Suffolk Downs
178,9817.00,02116,Beacon Hill,NaN,0,0,0.000000,0,0.000000,0,...,0,0.000000,0,0.000000,42.355087,-71.065743,Downtown Crossing,NaN,NaN,Boylston Street
179,9818.00,"02130, 02215",Jamaica Plain,NaN,26,9,0.346154,17,0.653846,0,...,4,0.153846,22,0.846154,42.323121,-71.116882,High Street Hill,NaN,NaN,Heath Street / Back of the Hill
180,9901.01,02130,NaN,NaN,67,18,0.268657,49,0.731343,0,...,55,0.820896,12,0.179104,42.329611,-70.949200,NaN,NaN,NaN,NaN

In [3]:
Neighborhoods_list = list(Sub_neighborhoods_df['Neighborhood'].unique())
Neighborhoods_list = Neighborhoods_list[0:-1]
Neighborhoods_list

['Brighton',
 'Allston',
 'Fenway',
 'Longwood Medical Area',
 'Back Bay',
 'Beacon Hill',
 'West End',
 'North End',
 'Downtown',
 'Charlestown',
 'East Boston',
 'South Boston',
 'South Boston Waterfront',
 'South End',
 'Roxbury',
 'Mission Hill',
 'Jamaica Plain',
 'Dorchester',
 'Mattapan',
 'Roslindale',
 'West Roxbury',
 'Hyde Park',
 'Harbor Islands']

In [5]:
Sub_neighborhoods_df['Primary Sub-Neighborhood']

0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object

In [46]:
test_df = Sub_neighborhoods_df[~Sub_neighborhoods_df['Primary Sub-Neighborhood'].isin(Neighborhoods_list)]
test_df

,Census Tract#,Zipcode,Neighborhood,US Geonames Sub-neigborhood,Total Population,Black,Black Proportion,White,White Proportion,American Indian & Alaska Native,...,Male,Male Proportion,Female,Female Proportion,Lat,Long,Primary Sub-Neighborhood,Secondary Sub-Neighborhood,Teritriary Sub-Neighborhood(s),T-Stop/Commuter Rail
0,1.00,"02134, 02135",Brighton,NaN,5324,311,0.058415,3315,0.622652,0,...,2578,0.484222,2746,0.515778,42.361485,-71.138588,Lower Allston,Allston,Packard's Corner,Boston Landing
1,2.01,02135,Brighton,NaN,3991,237,0.059384,3164,0.792784,17,...,1800,0.451015,2191,0.548985,42.354066,-71.161168,Oak Square,Brighton,Hunnewell Hill,NaN
2,2.02,02135,Brighton,NaN,4272,263,0.061564,3031,0.709504,0,...,2175,0.509129,2097,0.490871,42.352605,-71.154344,Oak Square,Brighton,Allston,NaN
3,3.01,02135,Brighton,NaN,2946,216,0.073320,2203,0.747794,0,...,1650,0.560081,1296,0.439919,42.354144,-71.168827,Hunnwell Hill,Oak Square,NaN,NaN
5,4.01,02135,Brighton,Aberdeen,5691,137,0.024073,4404,0.773853,34,...,2669,0.468986,3022,0.531014,42.343849,-71.149293,St. Elizabeth's,Oak Square,Corey Hill,Sutherland Road/Chiswick Road/Chestnut Hill Av...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,9815.02,02151,East Boston,NaN,0,0,0.000000,0,0.000000,0,...,0,0.000000,0,0.000000,42.396367,-71.004379,Beachmont,Orient Heights,NaN,Beachmont
177,9816.00,02128,East Boston,NaN,0,0,0.000000,0,0.000000,0,...,0,0.000000,0,0.000000,42.388621,-70.993442,Orient Heights,Beachmont,NaN,Suffolk Downs
178,9817.00,02116,Beacon Hill,NaN,0,0,0.000000,0,0.000000,0,...,0,0.000000,0,0.000000,42.355087,-71.065743,Downtown Crossing,NaN,NaN,Boylston Street
179,9818.00,"02130, 02215",Jamaica Plain,NaN,26,9,0.346154,17,0.653846,0,...,4,0.153846,22,0.846154,42.323121,-71.116882,High Street Hill,NaN,NaN,Heath Street / Back of the Hill
180,9901.01,02130,NaN,NaN,67,18,0.268657,49,0.731343,0,...,55,0.820896,12,0.179104,42.329611,-70.949200,NaN,NaN,NaN,NaN

In [52]:
Sub_neighborhoods_df["Primary Sub-Neighborhood"] = Sub_neighborhoods_df["Primary Sub-Neighborhood"].astype(str)

In [49]:
for neighborhood in Neighborhoods_list:
    Sub_neighborhoods_df["Primary Sub-Neighborhood"] = Sub_neighborhoods_df["Primary Sub-Neighborhood"].apply(lambda x: x.replace(neighborhood, ""))
    
Sub_neighborhoods_df

,Census Tract#,Zipcode,Neighborhood,US Geonames Sub-neigborhood,Total Population,Black,Black Proportion,White,White Proportion,American Indian & Alaska Native,...,Male,Male Proportion,Female,Female Proportion,Lat,Long,Primary Sub-Neighborhood,Secondary Sub-Neighborhood,Teritriary Sub-Neighborhood(s),T-Stop/Commuter Rail
0,1.00,"02134, 02135",Brighton,NaN,5324,311,0.058415,3315,0.622652,0,...,2578,0.484222,2746,0.515778,42.361485,-71.138588,Lower,Allston,Packard's Corner,Boston Landing
1,2.01,02135,Brighton,NaN,3991,237,0.059384,3164,0.792784,17,...,1800,0.451015,2191,0.548985,42.354066,-71.161168,Oak Square,Brighton,Hunnewell Hill,NaN
2,2.02,02135,Brighton,NaN,4272,263,0.061564,3031,0.709504,0,...,2175,0.509129,2097,0.490871,42.352605,-71.154344,Oak Square,Brighton,Allston,NaN
3,3.01,02135,Brighton,NaN,2946,216,0.073320,2203,0.747794,0,...,1650,0.560081,1296,0.439919,42.354144,-71.168827,Hunnwell Hill,Oak Square,NaN,NaN
4,3.02,02135,Brighton,NaN,3469,359,0.103488,2346,0.676276,25,...,1733,0.499568,1736,0.500432,42.347258,-71.167686,,St. Elizabeth's,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,9815.02,02151,East Boston,NaN,0,0,0.000000,0,0.000000,0,...,0,0.000000,0,0.000000,42.396367,-71.004379,Beachmont,Orient Heights,NaN,Beachmont
177,9816.00,02128,East Boston,NaN,0,0,0.000000,0,0.000000,0,...,0,0.000000,0,0.000000,42.388621,-70.993442,Orient Heights,Beachmont,NaN,Suffolk Downs
178,9817.00,02116,Beacon Hill,NaN,0,0,0.000000,0,0.000000,0,...,0,0.000000,0,0.000000,42.355087,-71.065743,Crossing,NaN,NaN,Boylston Street
179,9818.00,"02130, 02215",Jamaica Plain,NaN,26,9,0.346154,17,0.653846,0,...,4,0.153846,22,0.846154,42.323121,-71.116882,High Street Hill,NaN,NaN,Heath Street / Back of the Hill
180,9901.01,02130,NaN,NaN,67,18,0.268657,49,0.731343,0,...,55,0.820896,12,0.179104,42.329611,-70.949200,nan,NaN,NaN,NaN

In [23]:
for neighborhood in Neighborhoods_list:
    Sub_neighborhoods_df = Sub_neighborhoods_df.loc[Sub_neighborhoods_df['Primary Sub-Neighborhood'].str.contains(neighborhood), 'Primary Sub-Neighborhood'] = ''

Sub_neighborhoods_df

TypeError: string indices must be integers

In [27]:
Sub_neighborhoods_df.loc[Sub_neighborhoods_df['Primary Sub-Neighborhood'].str.contains('Allston'), 'Primary Sub-Neighborhood'] = ''

AttributeError: 'str' object has no attribute 'loc'

In [34]:
for neighborhood in Neighborhoods_list:
    print(neighborhood)
    print(type(neighborhood))

Brighton
<class 'str'>
Allston
<class 'str'>
Fenway
<class 'str'>
Longwood Medical Area
<class 'str'>
Back Bay
<class 'str'>
Beacon Hill
<class 'str'>
West End
<class 'str'>
North End
<class 'str'>
Downtown
<class 'str'>
Charlestown
<class 'str'>
East Boston
<class 'str'>
South Boston
<class 'str'>
South Boston Waterfront
<class 'str'>
South End
<class 'str'>
Roxbury
<class 'str'>
Mission Hill
<class 'str'>
Jamaica Plain
<class 'str'>
Dorchester
<class 'str'>
Mattapan
<class 'str'>
Roslindale
<class 'str'>
West Roxbury
<class 'str'>
Hyde Park
<class 'str'>
Harbor Islands
<class 'str'>

In [38]:
Sub_neighborhoods_df['Primary Sub-Neighborhood'] = Sub_neighborhoods_df['Primary Sub-Neighborhood'].replace("Allston", "")
Sub_neighborhoods_df

TypeError: string indices must be integers

In [32]:
for neighborhood in Neighborhoods_list:
    #neigh_term = "(^.*" + neighborhood + ".*$)"
    Sub_neighborhoods_df['Primary Sub-Neighborhood'] = Sub_neighborhoods_df['Primary Sub-Neighborhood'].str.replace(neighborhood, '')

Sub_neighborhoods_df

TypeError: string indices must be integers

In [41]:
#Sub_neighborhoods_df["Primary Sub-Neighborhood"] = Sub_neighborhoods_df["Primary Sub-Neighborhood"].apply(lambda x: x.replace(neighborhood, ""))
Sub_neighborhoods_df['support'][Sub_neighborhoods_df['Primary Sub-Neighborhood'].str.contains('Allston')] = ''

TypeError: string indices must be integers

In [42]:
Sub_neighborhoods_df.loc[Sub_neighborhoods_df['Primary Sub-Neighborhood'].str.contains('beverage'), 'Primary Sub-Neighborhood'] = 'beverage'

AttributeError: 'str' object has no attribute 'loc'

In [54]:
def selector(x):
    if 'Allston' in x:
        return " "
    if 'allston' in x:
        return " "
    

Sub_neighborhoods_df['Primary sub-neighborhoods edited'] = Sub_neighborhoods_df['Primary Sub-Neighborhood'].apply(selector)
Sub_neighborhoods_df

,Census Tract#,Zipcode,Neighborhood,US Geonames Sub-neigborhood,Total Population,Black,Black Proportion,White,White Proportion,American Indian & Alaska Native,...,Male Proportion,Female,Female Proportion,Lat,Long,Primary Sub-Neighborhood,Secondary Sub-Neighborhood,Teritriary Sub-Neighborhood(s),T-Stop/Commuter Rail,Primary sub-neighborhoods edited
0,1.00,"02134, 02135",Brighton,NaN,5324,311,0.058415,3315,0.622652,0,...,0.484222,2746,0.515778,42.361485,-71.138588,Lower Allston,Allston,Packard's Corner,Boston Landing,
1,2.01,02135,Brighton,NaN,3991,237,0.059384,3164,0.792784,17,...,0.451015,2191,0.548985,42.354066,-71.161168,Oak Square,Brighton,Hunnewell Hill,NaN,None
2,2.02,02135,Brighton,NaN,4272,263,0.061564,3031,0.709504,0,...,0.509129,2097,0.490871,42.352605,-71.154344,Oak Square,Brighton,Allston,NaN,None
3,3.01,02135,Brighton,NaN,2946,216,0.073320,2203,0.747794,0,...,0.560081,1296,0.439919,42.354144,-71.168827,Hunnwell Hill,Oak Square,NaN,NaN,None
4,3.02,02135,Brighton,NaN,3469,359,0.103488,2346,0.676276,25,...,0.499568,1736,0.500432,42.347258,-71.167686,Brighton,St. Elizabeth's,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,9815.02,02151,East Boston,NaN,0,0,0.000000,0,0.000000,0,...,0.000000,0,0.000000,42.396367,-71.004379,Beachmont,Orient Heights,NaN,Beachmont,None
177,9816.00,02128,East Boston,NaN,0,0,0.000000,0,0.000000,0,...,0.000000,0,0.000000,42.388621,-70.993442,Orient Heights,Beachmont,NaN,Suffolk Downs,None
178,9817.00,02116,Beacon Hill,NaN,0,0,0.000000,0,0.000000,0,...,0.000000,0,0.000000,42.355087,-71.065743,Downtown Crossing,NaN,NaN,Boylston Street,None
179,9818.00,"02130, 02215",Jamaica Plain,NaN,26,9,0.346154,17,0.653846,0,...,0.153846,22,0.846154,42.323121,-71.116882,High Street Hill,NaN,NaN,Heath Street / Back of the Hill,None
180,9901.01,02130,NaN,NaN,67,18,0.268657,49,0.731343,0,...,0.820896,12,0.179104,42.329611,-70.949200,nan,NaN,NaN,NaN,None

In [6]:
#Sub_neighborhoods_df['Primary Sub-Neighborhood Edit'] = ['' for names in Sub_neighborhoods_df['Primary Sub-Neighborhood'] for neigh in Neighborhoods_list if names == neigh]
#Sub_neighborhoods_df

ValueError: Length of values (45) does not match length of index (181)

In [8]:
Sub_neigh_list_clean = []
for names in Sub_neighborhoods_df['Primary Sub-Neighborhood']:
    if names in Neighborhoods_list:
        Sub_neigh_list_clean.append('')
    else:
        Sub_neigh_list_clean.append(names)

Sub_neighborhoods_df['Primary Sub-Neighborhood Cleaned'] = Sub_neigh_list_clean
Sub_neighborhoods_df

,Census Tract#,Zipcode,Neighborhood,US Geonames Sub-neigborhood,Total Population,Black,Black Proportion,White,White Proportion,American Indian & Alaska Native,...,Male Proportion,Female,Female Proportion,Lat,Long,Primary Sub-Neighborhood,Secondary Sub-Neighborhood,Teritriary Sub-Neighborhood(s),T-Stop/Commuter Rail,Primary Sub-Neighborhood Cleaned
0,1.00,"02134, 02135",Brighton,NaN,5324,311,0.058415,3315,0.622652,0,...,0.484222,2746,0.515778,42.361485,-71.138588,Lower Allston,Allston,Packard's Corner,Boston Landing,Lower Allston
1,2.01,02135,Brighton,NaN,3991,237,0.059384,3164,0.792784,17,...,0.451015,2191,0.548985,42.354066,-71.161168,Oak Square,Brighton,Hunnewell Hill,NaN,Oak Square
2,2.02,02135,Brighton,NaN,4272,263,0.061564,3031,0.709504,0,...,0.509129,2097,0.490871,42.352605,-71.154344,Oak Square,Brighton,Allston,NaN,Oak Square
3,3.01,02135,Brighton,NaN,2946,216,0.073320,2203,0.747794,0,...,0.560081,1296,0.439919,42.354144,-71.168827,Hunnwell Hill,Oak Square,NaN,NaN,Hunnwell Hill
4,3.02,02135,Brighton,NaN,3469,359,0.103488,2346,0.676276,25,...,0.499568,1736,0.500432,42.347258,-71.167686,Brighton,St. Elizabeth's,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,9815.02,02151,East Boston,NaN,0,0,0.000000,0,0.000000,0,...,0.000000,0,0.000000,42.396367,-71.004379,Beachmont,Orient Heights,NaN,Beachmont,Beachmont
177,9816.00,02128,East Boston,NaN,0,0,0.000000,0,0.000000,0,...,0.000000,0,0.000000,42.388621,-70.993442,Orient Heights,Beachmont,NaN,Suffolk Downs,Orient Heights
178,9817.00,02116,Beacon Hill,NaN,0,0,0.000000,0,0.000000,0,...,0.000000,0,0.000000,42.355087,-71.065743,Downtown Crossing,NaN,NaN,Boylston Street,Downtown Crossing
179,9818.00,"02130, 02215",Jamaica Plain,NaN,26,9,0.346154,17,0.653846,0,...,0.153846,22,0.846154,42.323121,-71.116882,High Street Hill,NaN,NaN,Heath Street / Back of the Hill,High Street Hill
180,9901.01,02130,NaN,NaN,67,18,0.268657,49,0.731343,0,...,0.820896,12,0.179104,42.329611,-70.949200,NaN,NaN,NaN,NaN,NaN

In [9]:
Secondary_Sub_neigh_list_clean = []
for names in Sub_neighborhoods_df['Secondary Sub-Neighborhood']:
    if names in Neighborhoods_list:
        Secondary_Sub_neigh_list_clean.append('')
    else:
        Secondary_Sub_neigh_list_clean.append(names)

Sub_neighborhoods_df['Secondary Sub-Neighborhood Cleaned'] = Secondary_Sub_neigh_list_clean
Sub_neighborhoods_df

,Census Tract#,Zipcode,Neighborhood,US Geonames Sub-neigborhood,Total Population,Black,Black Proportion,White,White Proportion,American Indian & Alaska Native,...,Female,Female Proportion,Lat,Long,Primary Sub-Neighborhood,Secondary Sub-Neighborhood,Teritriary Sub-Neighborhood(s),T-Stop/Commuter Rail,Primary Sub-Neighborhood Cleaned,Secondary Sub-Neighborhood Cleaned
0,1.00,"02134, 02135",Brighton,NaN,5324,311,0.058415,3315,0.622652,0,...,2746,0.515778,42.361485,-71.138588,Lower Allston,Allston,Packard's Corner,Boston Landing,Lower Allston,
1,2.01,02135,Brighton,NaN,3991,237,0.059384,3164,0.792784,17,...,2191,0.548985,42.354066,-71.161168,Oak Square,Brighton,Hunnewell Hill,NaN,Oak Square,
2,2.02,02135,Brighton,NaN,4272,263,0.061564,3031,0.709504,0,...,2097,0.490871,42.352605,-71.154344,Oak Square,Brighton,Allston,NaN,Oak Square,
3,3.01,02135,Brighton,NaN,2946,216,0.073320,2203,0.747794,0,...,1296,0.439919,42.354144,-71.168827,Hunnwell Hill,Oak Square,NaN,NaN,Hunnwell Hill,Oak Square
4,3.02,02135,Brighton,NaN,3469,359,0.103488,2346,0.676276,25,...,1736,0.500432,42.347258,-71.167686,Brighton,St. Elizabeth's,NaN,NaN,,St. Elizabeth's
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,9815.02,02151,East Boston,NaN,0,0,0.000000,0,0.000000,0,...,0,0.000000,42.396367,-71.004379,Beachmont,Orient Heights,NaN,Beachmont,Beachmont,Orient Heights
177,9816.00,02128,East Boston,NaN,0,0,0.000000,0,0.000000,0,...,0,0.000000,42.388621,-70.993442,Orient Heights,Beachmont,NaN,Suffolk Downs,Orient Heights,Beachmont
178,9817.00,02116,Beacon Hill,NaN,0,0,0.000000,0,0.000000,0,...,0,0.000000,42.355087,-71.065743,Downtown Crossing,NaN,NaN,Boylston Street,Downtown Crossing,NaN
179,9818.00,"02130, 02215",Jamaica Plain,NaN,26,9,0.346154,17,0.653846,0,...,22,0.846154,42.323121,-71.116882,High Street Hill,NaN,NaN,Heath Street / Back of the Hill,High Street Hill,NaN
180,9901.01,02130,NaN,NaN,67,18,0.268657,49,0.731343,0,...,12,0.179104,42.329611,-70.949200,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
Teritiary_Sub_neigh_list_clean = []
for names in Sub_neighborhoods_df['Teritriary Sub-Neighborhood(s)']:
    if names in Neighborhoods_list:
        Teritiary_Sub_neigh_list_clean.append('')
    else:
        Teritiary_Sub_neigh_list_clean.append(names)

Sub_neighborhoods_df['Teritiary Sub-Neighborhood(s) Cleaned'] = Teritiary_Sub_neigh_list_clean
Sub_neighborhoods_df

,Census Tract#,Zipcode,Neighborhood,US Geonames Sub-neigborhood,Total Population,Black,Black Proportion,White,White Proportion,American Indian & Alaska Native,...,Female Proportion,Lat,Long,Primary Sub-Neighborhood,Secondary Sub-Neighborhood,Teritriary Sub-Neighborhood(s),T-Stop/Commuter Rail,Primary Sub-Neighborhood Cleaned,Secondary Sub-Neighborhood Cleaned,Teritiary Sub-Neighborhood(s) Cleaned
0,1.00,"02134, 02135",Brighton,NaN,5324,311,0.058415,3315,0.622652,0,...,0.515778,42.361485,-71.138588,Lower Allston,Allston,Packard's Corner,Boston Landing,Lower Allston,,Packard's Corner
1,2.01,02135,Brighton,NaN,3991,237,0.059384,3164,0.792784,17,...,0.548985,42.354066,-71.161168,Oak Square,Brighton,Hunnewell Hill,NaN,Oak Square,,Hunnewell Hill
2,2.02,02135,Brighton,NaN,4272,263,0.061564,3031,0.709504,0,...,0.490871,42.352605,-71.154344,Oak Square,Brighton,Allston,NaN,Oak Square,,
3,3.01,02135,Brighton,NaN,2946,216,0.073320,2203,0.747794,0,...,0.439919,42.354144,-71.168827,Hunnwell Hill,Oak Square,NaN,NaN,Hunnwell Hill,Oak Square,NaN
4,3.02,02135,Brighton,NaN,3469,359,0.103488,2346,0.676276,25,...,0.500432,42.347258,-71.167686,Brighton,St. Elizabeth's,NaN,NaN,,St. Elizabeth's,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,9815.02,02151,East Boston,NaN,0,0,0.000000,0,0.000000,0,...,0.000000,42.396367,-71.004379,Beachmont,Orient Heights,NaN,Beachmont,Beachmont,Orient Heights,NaN
177,9816.00,02128,East Boston,NaN,0,0,0.000000,0,0.000000,0,...,0.000000,42.388621,-70.993442,Orient Heights,Beachmont,NaN,Suffolk Downs,Orient Heights,Beachmont,NaN
178,9817.00,02116,Beacon Hill,NaN,0,0,0.000000,0,0.000000,0,...,0.000000,42.355087,-71.065743,Downtown Crossing,NaN,NaN,Boylston Street,Downtown Crossing,NaN,NaN
179,9818.00,"02130, 02215",Jamaica Plain,NaN,26,9,0.346154,17,0.653846,0,...,0.846154,42.323121,-71.116882,High Street Hill,NaN,NaN,Heath Street / Back of the Hill,High Street Hill,NaN,NaN
180,9901.01,02130,NaN,NaN,67,18,0.268657,49,0.731343,0,...,0.179104,42.329611,-70.949200,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
from pandas import ExcelWriter
from pandas import ExcelFile

with ExcelWriter('Revised_Sub-Neighborhoods_Cleaned.xlsx') as writer:
    Sub_neighborhoods_df.to_excel(writer)

# Further Cleaning 01/14/2021

In [2]:
Sub_neighborhoods_df = pd.read_excel('Revised_Sub-Neighborhoods_Cleaned.xlsx')
Sub_neighborhoods_df

,Unnamed: 0,Census Tract#,Zipcode,Neighborhood,US Geonames Sub-neigborhood,Total Population,Black,Black Proportion,White,White Proportion,...,Female Proportion,Lat,Long,Primary Sub-Neighborhood,Secondary Sub-Neighborhood,Teritriary Sub-Neighborhood(s),T-Stop/Commuter Rail,Primary Sub-Neighborhood Cleaned,Secondary Sub-Neighborhood Cleaned,Teritiary Sub-Neighborhood(s) Cleaned
0,0,1.00,"02134, 02135",Brighton,NaN,5324,311,0.058415,3315,0.622652,...,0.515778,42.361485,-71.138588,Lower Allston,Allston,Packard's Corner,Boston Landing,Lower Allston,NaN,Packard's Corner
1,1,2.01,02135,Brighton,NaN,3991,237,0.059384,3164,0.792784,...,0.548985,42.354066,-71.161168,Oak Square,Brighton,Hunnewell Hill,NaN,Oak Square,NaN,Hunnewell Hill
2,2,2.02,02135,Brighton,NaN,4272,263,0.061564,3031,0.709504,...,0.490871,42.352605,-71.154344,Oak Square,Brighton,Allston,NaN,Oak Square,NaN,NaN
3,3,3.01,02135,Brighton,NaN,2946,216,0.073320,2203,0.747794,...,0.439919,42.354144,-71.168827,Hunnwell Hill,Oak Square,NaN,NaN,Hunnwell Hill,Oak Square,NaN
4,4,3.02,02135,Brighton,NaN,3469,359,0.103488,2346,0.676276,...,0.500432,42.347258,-71.167686,Brighton,St. Elizabeth's,NaN,NaN,NaN,St. Elizabeth's,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,176,9815.02,02151,East Boston,NaN,0,0,0.000000,0,0.000000,...,0.000000,42.396367,-71.004379,Beachmont,Orient Heights,NaN,Beachmont,Beachmont,Orient Heights,NaN
177,177,9816.00,02128,East Boston,NaN,0,0,0.000000,0,0.000000,...,0.000000,42.388621,-70.993442,Orient Heights,Beachmont,NaN,Suffolk Downs,Orient Heights,Beachmont,NaN
178,178,9817.00,02116,Beacon Hill,NaN,0,0,0.000000,0,0.000000,...,0.000000,42.355087,-71.065743,Downtown Crossing,NaN,NaN,Boylston Street,Downtown Crossing,NaN,NaN
179,179,9818.00,"02130, 02215",Jamaica Plain,NaN,26,9,0.346154,17,0.653846,...,0.846154,42.323121,-71.116882,High Street Hill,NaN,NaN,Heath Street / Back of the Hill,High Street Hill,NaN,NaN
180,180,9901.01,02130,NaN,NaN,67,18,0.268657,49,0.731343,...,0.179104,42.329611,-70.949200,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
print(Sub_neighborhoods_df['Primary Sub-Neighborhood'].unique())

['Lower Allston' 'Oak Square' 'Hunnwell Hill' 'Brighton' "St. Elizabeth's"
 'Chestnut Hill Neighborhood Association' 'Aberdeen'
 'Salisbury Road-Corey Farm' 'Allston' 'Back Bay' 'West Fens'
 'Fenway-Kenmore' 'Frederick Douglas Square Historic District'
 'Back Bay West / Back Bay' 'West End' 'Bunker Hill' 'Charlestown'
 'Boston' 'East Boston' nan 'Medford Street/The Neck' 'Eagle Hill'
 'Central Maverick Square/Paris Square' 'Orient Heights'
 'Harbor View/Orient Heights' 'Jeffries Point' 'City Point'
 'Telegraph Hill' 'Seaport District' 'D Street / West Broadway'
 'South Boston' 'Columbus Park/Andrew Square' 'Downtown Crossing'
 'China Town' 'Bay Village' 'Shawmut' 'Columbus' 'South End'
 'Lower Roxbury' 'Nubian Square' 'Mission Hill' 'Central Village'
 'Fort Hill' 'Washington Park ' 'Washington Park' 'Roxbury' 'Grove Hall'
 'Franklin Field South' 'Bowdoin North/Mount Bodoin'
 'Dudley/Brunswick King' "Upham's Corner" 'Jones Hill'
 'Meeting House Hill' 'Dorchester' 'Clam Point' 'Fields Corner Wester'
 'Dorcehster Center' 'West Codman Hill/ West Lower Mills' 'Codman Square'
 'St. Marks' 'Neponset/Port Norfolk' 'Adams Village' 'Ashmount'
 'Milton Hill' 'Southern Mattapan' 'Mattapan' 'Wellington Hill'
 'Washington Hill' 'Forest Hills/Woodbourne' 'Washington /Mount Hope'
 'Roslindale ' 'Metropolitan Hill/Beech Street' 'Roslindale'
 'Centre South' 'Jamaica Hills' 'Jamaica Plain' 'Stonybrook' 'Roxbury '
 'Egleston Square' 'High Street Hill' 'Brook Farm' 'Bellevue Hill'
 'Upper Washington/Spring Street' 'Hyde Park' 'Georgetown'
 'West Street/River Street' 'Ashcroft' 'Beachmont']

In [4]:
print(Sub_neighborhoods_df['Secondary Sub-Neighborhood'].unique())

['Allston' 'Brighton' 'Oak Square' "St. Elizabeth's" 'Fisher Hill'
 'Salisbury Road-Corey Farm' 'Aberdeen' 'Corey Hill' nan 'Lower Alston'
 'Cambridgeport' "Packard's Corner" 'Fenway-Kenmore'
 'Cottage Farm Historic District' 'Medical Center Area' 'Columbus'
 'South End' 'Kenmore' 'East Cambridge' 'Bay Village' 'Waterfront'
 'Medford Street/The Neck' 'West End' 'Bunker Hill' 'Charlestown'
 'Inner Belt' 'Admirals Hill' 'Central Square' 'Jeffries Point'
 'Jerffries Point' 'East Boston' 'Chelsea' 'Winthrop'
 'Central Maverick Square/Paris Street' 'Telegraph Hill' 'City Point'
 'D Street/West Broadway' 'Fort Point' 'South Boston'
 'Columbus Park / Andrew Square' 'China Town' 'Columbus ' 'Shawmut'
 'Lower Roxbury' 'Frederick Douglas Square Historic District'
 'Central Village' 'Mission Hill' 'High Street Hill' 'Roxbury' 'Fort Hill'
 'Washington Park' 'Dudley/Brunswick King' 'Bowdoin North / Mount Bowdoin'
 'Grove Hall' 'Jones Hill' "Upham's Corner" 'Nubian Square'
 'Meeting House Hill' 'Dorchester' 'Gorve Hall' 'Franklin Field North'
 'Fields Corner West' 'St. Marks' 'Codman Square'
 'West Codman Hill / West Lower Mills' 'Ashmont' 'Dorchester Center'
 'Neponset/Port Norfolk' 'Marina Bay' 'Mattapan' 'Stony Brook'
 'Roslindale' 'Lower Washington/Mount Hope'
 'Metropolitan Hill/Beech Street' 'South Brookline' 'Jamaica Plain'
 'Jamaica Hills' 'Oak Hill Park' 'West Roxbury' 'West Street/River Street'
 'Fairmount Hill' 'Readville' 'Upper Washington / Spring Street'
 'Orient Heights' 'Beachmont']

In [5]:
print(Sub_neighborhoods_df['Teritriary Sub-Neighborhood(s)'].unique())

["Packard's Corner" 'Hunnewell Hill' 'Allston' nan 'Corey Hill'
 'Aberdeen/Oak Square' 'Aberdeen' 'Longwood' 'Columbus'
 'Frederick Douglas Square Historic District' 'Bay Village' 'Charlestown'
 'Waterfront' 'Jeffries Point' 'Medford Street/ The Neck' 'Bunker Hill'
 'Assembly Square' 'Eagle Hill' 'Chelsea' 'East Boston' 'Central Square'
 'South Boston' 'Columbus Park/Andrew Square' 'Seaport District'
 'Telegraph Hill' 'Shawmut' 'Boston Theater District' 'Back Bay/West End'
 'South End' 'South End  ' 'Fenway-Kenmore' 'Lower Roxbury '
 'South End of Washington' 'Nubian Square' 'Central Village' 'Brookline'
 'Egleston Square' 'Meeting House Hall' "Upham's Corner" 'Grove Hall'
 'Dudley/Brunswick King' 'Jones Hill' 'Bowdoin North/Mount Bodoin'
 'Dorchester' 'Washington/Mount Hope' 'Washington Park'
 'West Street / River Street' 'Hyde Park' 'Forest Hills Woodbourne'
 'Lower Washington/Mount Hope' 'D Street/West Broadway']

In [6]:
Neighborhoods_list = list(Sub_neighborhoods_df['Neighborhood'].unique())
Neighborhoods_list = Neighborhoods_list[0:-1]
Neighborhoods_list

['Brighton',
 'Allston',
 'Fenway',
 'Longwood Medical Area',
 'Back Bay',
 'Beacon Hill',
 'West End',
 'North End',
 'Downtown',
 'Charlestown',
 'East Boston',
 'South Boston',
 'South Boston Waterfront',
 'South End',
 'Roxbury',
 'Mission Hill',
 'Jamaica Plain',
 'Dorchester',
 'Mattapan',
 'Roslindale',
 'West Roxbury',
 'Hyde Park',
 'Harbor Islands']

In [12]:
for neighborhood in Neighborhoods_list:
    #test_df = Sub_neighborhoods_df[Sub_neighborhoods_df['Primary Sub-Neighborhood'].str.contains(neighborhood, na=False, case=False)]
    print(Sub_neighborhoods_df['Primary Sub-Neighborhood'].str.replace(neighborhood, ''))
    #print(Sub_neighborhoods_df)

0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0                 Lower
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0         Lower Allston
1            Oak Square
2            Oak Square
3         Hunnwell Hill
4              Brighton
             ...
176           Beachmont
177      Orient Heights
178            Crossing
179    High Street Hill
180                 NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object
0          Lower Allston
1             Oak Square
2             Oak Square
3          Hunnwell Hill
4               Brighton
             ...
176            Beachmont
177       Orient Heights
178    Downtown Crossing
179     High Street Hill
180                  NaN
Name: Primary Sub-Neighborhood, Length: 181, dtype: object